name: pronoun
dependencies:
- freetype=2.5.2=0
- ipython=3.1.0=py34_0
- libpng=1.5.13=1
- matplotlib=1.4.3=np19py34_1
- numpy=1.9.2=py34_0
- openssl=1.0.1k=1
- pandas=0.16.0=np19py34_1
- pip=6.0.8=py34_0
- pyparsing=2.0.3=py34_0
- python=3.4.3=0
- python-dateutil=2.4.2=py34_0
- python.app=1.2=py34_3
- pytz=2015.2=py34_0
- readline=6.2=2
- scipy=0.15.1=np19py34_0
- setuptools=14.3.1=py34_0
- six=1.9.0=py34_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- xz=5.0.5=0
- zlib=1.2.8=0
- pip:
  - alembic==0.7.5.post2
  - dataset==0.5.6
  - expy==0.1.0
  - gitdb==0.6.4
  - gitpython==0.3.6
  - mako==1.0.1
  - markupsafe==0.23
  - nose==1.3.4
  - pymysql==0.6.6
  - python-slugify==0.1.0
  - pyyaml==3.11
  - scikit-learn==0.16.0
  - smmap==0.9.0
  - sqlalchemy==1.0.0b5
  - unidecode==0.4.17

